// Code generated by qtc from "jaeger.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vtselect/traces/jaeger/jaeger.qtpl:1
package jaeger

//line app/vtselect/traces/jaeger/jaeger.qtpl:1
import (
	"sort"
)

//line app/vtselect/traces/jaeger/jaeger.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vtselect/traces/jaeger/jaeger.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vtselect/traces/jaeger/jaeger.qtpl:7
func StreamGetServicesResponse(qw422016 *qt422016.Writer, serviceList []string) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:7
	qw422016.N().S(`{`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:10
	sort.Slice(serviceList, func(i, j int) bool { return serviceList[i] < serviceList[j] })

//line app/vtselect/traces/jaeger/jaeger.qtpl:11
	qw422016.N().S(`"data":[`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:13
	if len(serviceList) > 0 {
//line app/vtselect/traces/jaeger/jaeger.qtpl:14
		qw422016.N().Q(serviceList[0])
//line app/vtselect/traces/jaeger/jaeger.qtpl:15
		for _, service := range serviceList[1:] {
//line app/vtselect/traces/jaeger/jaeger.qtpl:15
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:16
			qw422016.N().Q(service)
//line app/vtselect/traces/jaeger/jaeger.qtpl:17
		}
//line app/vtselect/traces/jaeger/jaeger.qtpl:18
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:18
	qw422016.N().S(`],"errors": null,"limit": 0,"offset": 0,"total":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:23
	qw422016.N().D(len(serviceList))
//line app/vtselect/traces/jaeger/jaeger.qtpl:23
	qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:25
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:25
func WriteGetServicesResponse(qq422016 qtio422016.Writer, serviceList []string) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:25
	StreamGetServicesResponse(qw422016, serviceList)
//line app/vtselect/traces/jaeger/jaeger.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:25
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:25
func GetServicesResponse(serviceList []string) string {
//line app/vtselect/traces/jaeger/jaeger.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/jaeger.qtpl:25
	WriteGetServicesResponse(qb422016, serviceList)
//line app/vtselect/traces/jaeger/jaeger.qtpl:25
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/jaeger.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:25
	return qs422016
//line app/vtselect/traces/jaeger/jaeger.qtpl:25
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:27
func StreamGetOperationsResponse(qw422016 *qt422016.Writer, operationList []string) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:27
	qw422016.N().S(`{`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:30
	sort.Slice(operationList, func(i, j int) bool { return operationList[i] < operationList[j] })

//line app/vtselect/traces/jaeger/jaeger.qtpl:31
	qw422016.N().S(`"data":[`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:33
	if len(operationList) > 0 {
//line app/vtselect/traces/jaeger/jaeger.qtpl:34
		qw422016.N().Q(operationList[0])
//line app/vtselect/traces/jaeger/jaeger.qtpl:35
		for _, operation := range operationList[1:] {
//line app/vtselect/traces/jaeger/jaeger.qtpl:35
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:36
			qw422016.N().Q(operation)
//line app/vtselect/traces/jaeger/jaeger.qtpl:37
		}
//line app/vtselect/traces/jaeger/jaeger.qtpl:38
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:38
	qw422016.N().S(`],"errors": null,"limit": 0,"offset": 0,"total":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:43
	qw422016.N().D(len(operationList))
//line app/vtselect/traces/jaeger/jaeger.qtpl:43
	qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:45
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:45
func WriteGetOperationsResponse(qq422016 qtio422016.Writer, operationList []string) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:45
	StreamGetOperationsResponse(qw422016, operationList)
//line app/vtselect/traces/jaeger/jaeger.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:45
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:45
func GetOperationsResponse(operationList []string) string {
//line app/vtselect/traces/jaeger/jaeger.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/jaeger.qtpl:45
	WriteGetOperationsResponse(qb422016, operationList)
//line app/vtselect/traces/jaeger/jaeger.qtpl:45
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/jaeger.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:45
	return qs422016
//line app/vtselect/traces/jaeger/jaeger.qtpl:45
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:47
func StreamGetTracesResponse(qw422016 *qt422016.Writer, traces []*trace) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:47
	qw422016.N().S(`{"data":[`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:50
	if len(traces) > 0 && len(traces[0].spans) > 0 {
//line app/vtselect/traces/jaeger/jaeger.qtpl:51
		streamtraceJson(qw422016, traces[0])
//line app/vtselect/traces/jaeger/jaeger.qtpl:52
		for _, trace := range traces[1:] {
//line app/vtselect/traces/jaeger/jaeger.qtpl:53
			if len(trace.spans) > 0 {
//line app/vtselect/traces/jaeger/jaeger.qtpl:53
				qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:54
				streamtraceJson(qw422016, trace)
//line app/vtselect/traces/jaeger/jaeger.qtpl:55
			}
//line app/vtselect/traces/jaeger/jaeger.qtpl:56
		}
//line app/vtselect/traces/jaeger/jaeger.qtpl:57
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:57
	qw422016.N().S(`],"errors": null,"limit": 0,"offset": 0,"total":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:62
	qw422016.N().D(len(traces))
//line app/vtselect/traces/jaeger/jaeger.qtpl:62
	qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:64
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:64
func WriteGetTracesResponse(qq422016 qtio422016.Writer, traces []*trace) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:64
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:64
	StreamGetTracesResponse(qw422016, traces)
//line app/vtselect/traces/jaeger/jaeger.qtpl:64
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:64
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:64
func GetTracesResponse(traces []*trace) string {
//line app/vtselect/traces/jaeger/jaeger.qtpl:64
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/jaeger.qtpl:64
	WriteGetTracesResponse(qb422016, traces)
//line app/vtselect/traces/jaeger/jaeger.qtpl:64
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/jaeger.qtpl:64
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:64
	return qs422016
//line app/vtselect/traces/jaeger/jaeger.qtpl:64
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:66
func StreamGetTraceResponse(qw422016 *qt422016.Writer, trace *trace) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:66
	qw422016.N().S(`{"data":[`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:69
	if trace != nil {
//line app/vtselect/traces/jaeger/jaeger.qtpl:70
		streamtraceJson(qw422016, trace)
//line app/vtselect/traces/jaeger/jaeger.qtpl:71
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:71
	qw422016.N().S(`],"errors":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:74
	if trace == nil {
//line app/vtselect/traces/jaeger/jaeger.qtpl:74
		qw422016.N().S(`[{"code":404,"msg":"trace not found"}]`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:76
	} else {
//line app/vtselect/traces/jaeger/jaeger.qtpl:76
		qw422016.N().S(`null`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:78
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:78
	qw422016.N().S(`,"limit": 0,"offset": 0,"total":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:82
	if trace == nil {
//line app/vtselect/traces/jaeger/jaeger.qtpl:82
		qw422016.N().S(`0`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:82
	} else {
//line app/vtselect/traces/jaeger/jaeger.qtpl:82
		qw422016.N().S(`1`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:82
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:82
	qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:84
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:84
func WriteGetTraceResponse(qq422016 qtio422016.Writer, trace *trace) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:84
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:84
	StreamGetTraceResponse(qw422016, trace)
//line app/vtselect/traces/jaeger/jaeger.qtpl:84
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:84
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:84
func GetTraceResponse(trace *trace) string {
//line app/vtselect/traces/jaeger/jaeger.qtpl:84
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/jaeger.qtpl:84
	WriteGetTraceResponse(qb422016, trace)
//line app/vtselect/traces/jaeger/jaeger.qtpl:84
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/jaeger.qtpl:84
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:84
	return qs422016
//line app/vtselect/traces/jaeger/jaeger.qtpl:84
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:86
func StreamGetDependenciesResponse(qw422016 *qt422016.Writer, dependencies []*dependencyLink) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:86
	qw422016.N().S(`{"data":[`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:89
	if len(dependencies) > 0 {
//line app/vtselect/traces/jaeger/jaeger.qtpl:90
		streamdependencyJson(qw422016, dependencies[0])
//line app/vtselect/traces/jaeger/jaeger.qtpl:91
		for _, dependency := range dependencies[1:] {
//line app/vtselect/traces/jaeger/jaeger.qtpl:91
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:92
			streamdependencyJson(qw422016, dependency)
//line app/vtselect/traces/jaeger/jaeger.qtpl:93
		}
//line app/vtselect/traces/jaeger/jaeger.qtpl:94
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:94
	qw422016.N().S(`],"errors": null,"limit": 0,"offset": 0,"total":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:99
	qw422016.N().D(len(dependencies))
//line app/vtselect/traces/jaeger/jaeger.qtpl:99
	qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:101
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:101
func WriteGetDependenciesResponse(qq422016 qtio422016.Writer, dependencies []*dependencyLink) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:101
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:101
	StreamGetDependenciesResponse(qw422016, dependencies)
//line app/vtselect/traces/jaeger/jaeger.qtpl:101
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:101
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:101
func GetDependenciesResponse(dependencies []*dependencyLink) string {
//line app/vtselect/traces/jaeger/jaeger.qtpl:101
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/jaeger.qtpl:101
	WriteGetDependenciesResponse(qb422016, dependencies)
//line app/vtselect/traces/jaeger/jaeger.qtpl:101
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/jaeger.qtpl:101
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:101
	return qs422016
//line app/vtselect/traces/jaeger/jaeger.qtpl:101
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:103
func streamdependencyJson(qw422016 *qt422016.Writer, dependency *dependencyLink) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:103
	qw422016.N().S(`{"parent":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:105
	qw422016.N().Q(dependency.parent)
//line app/vtselect/traces/jaeger/jaeger.qtpl:105
	qw422016.N().S(`,"child":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:106
	qw422016.N().Q(dependency.child)
//line app/vtselect/traces/jaeger/jaeger.qtpl:106
	qw422016.N().S(`,"callCount":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:107
	qw422016.N().DUL(dependency.callCount)
//line app/vtselect/traces/jaeger/jaeger.qtpl:107
	qw422016.N().S(`,"warningCount":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:108
	qw422016.N().DUL(dependency.warningCount)
//line app/vtselect/traces/jaeger/jaeger.qtpl:108
	qw422016.N().S(`,"errorCount":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:109
	qw422016.N().DUL(dependency.errorCount)
//line app/vtselect/traces/jaeger/jaeger.qtpl:109
	qw422016.N().S(`,"normalCount":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:110
	qw422016.N().DUL(dependency.normalCount)
//line app/vtselect/traces/jaeger/jaeger.qtpl:110
	qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:112
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:109
func writedependencyJson(qq422016 qtio422016.Writer, dependency *dependencyLink) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:109
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:109
	streamdependencyJson(qw422016, dependency)
//line app/vtselect/traces/jaeger/jaeger.qtpl:109
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:109
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:109
func dependencyJson(dependency *dependencyLink) string {
//line app/vtselect/traces/jaeger/jaeger.qtpl:109
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/jaeger.qtpl:109
	writedependencyJson(qb422016, dependency)
//line app/vtselect/traces/jaeger/jaeger.qtpl:109
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/jaeger.qtpl:109
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:109
	return qs422016
//line app/vtselect/traces/jaeger/jaeger.qtpl:109
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:111
func streamtraceJson(qw422016 *qt422016.Writer, trace *trace) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:111
	qw422016.N().S(`{"processes": {`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:114
	if len(trace.processMap) > 0 {
//line app/vtselect/traces/jaeger/jaeger.qtpl:115
		qw422016.N().Q(trace.processMap[0].processID)
//line app/vtselect/traces/jaeger/jaeger.qtpl:115
		qw422016.N().S(`:`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:115
		streamprocessJson(qw422016, trace.processMap[0].process)
//line app/vtselect/traces/jaeger/jaeger.qtpl:116
		for _, v := range trace.processMap[1:] {
//line app/vtselect/traces/jaeger/jaeger.qtpl:116
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:117
			qw422016.N().Q(v.processID)
//line app/vtselect/traces/jaeger/jaeger.qtpl:117
			qw422016.N().S(`:`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:117
			streamprocessJson(qw422016, v.process)
//line app/vtselect/traces/jaeger/jaeger.qtpl:118
		}
//line app/vtselect/traces/jaeger/jaeger.qtpl:119
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:119
	qw422016.N().S(`},"spans": [`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:122
	if len(trace.spans) > 0 {
//line app/vtselect/traces/jaeger/jaeger.qtpl:123
		streamspanJson(qw422016, trace.spans[0])
//line app/vtselect/traces/jaeger/jaeger.qtpl:124
		for _, v := range trace.spans[1:] {
//line app/vtselect/traces/jaeger/jaeger.qtpl:124
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:125
			streamspanJson(qw422016, v)
//line app/vtselect/traces/jaeger/jaeger.qtpl:126
		}
//line app/vtselect/traces/jaeger/jaeger.qtpl:127
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:127
	qw422016.N().S(`],"traceID":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:129
	qw422016.N().Q(trace.spans[0].traceID)
//line app/vtselect/traces/jaeger/jaeger.qtpl:129
	qw422016.N().S(`,"warnings": null}`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:132
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:132
func writetraceJson(qq422016 qtio422016.Writer, trace *trace) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:132
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:132
	streamtraceJson(qw422016, trace)
//line app/vtselect/traces/jaeger/jaeger.qtpl:132
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:132
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:132
func traceJson(trace *trace) string {
//line app/vtselect/traces/jaeger/jaeger.qtpl:132
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/jaeger.qtpl:132
	writetraceJson(qb422016, trace)
//line app/vtselect/traces/jaeger/jaeger.qtpl:132
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/jaeger.qtpl:132
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:132
	return qs422016
//line app/vtselect/traces/jaeger/jaeger.qtpl:132
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:134
func streamprocessJson(qw422016 *qt422016.Writer, process process) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:134
	qw422016.N().S(`{"serviceName":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:136
	qw422016.N().Q(process.serviceName)
//line app/vtselect/traces/jaeger/jaeger.qtpl:136
	qw422016.N().S(`,"tags": [`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:138
	if len(process.tags) > 0 {
//line app/vtselect/traces/jaeger/jaeger.qtpl:139
		streamtagJson(qw422016, process.tags[0])
//line app/vtselect/traces/jaeger/jaeger.qtpl:140
		for _, v := range process.tags[1:] {
//line app/vtselect/traces/jaeger/jaeger.qtpl:140
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:141
			streamtagJson(qw422016, v)
//line app/vtselect/traces/jaeger/jaeger.qtpl:142
		}
//line app/vtselect/traces/jaeger/jaeger.qtpl:143
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:143
	qw422016.N().S(`]}`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:146
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:146
func writeprocessJson(qq422016 qtio422016.Writer, process process) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:146
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:146
	streamprocessJson(qw422016, process)
//line app/vtselect/traces/jaeger/jaeger.qtpl:146
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:146
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:146
func processJson(process process) string {
//line app/vtselect/traces/jaeger/jaeger.qtpl:146
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/jaeger.qtpl:146
	writeprocessJson(qb422016, process)
//line app/vtselect/traces/jaeger/jaeger.qtpl:146
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/jaeger.qtpl:146
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:146
	return qs422016
//line app/vtselect/traces/jaeger/jaeger.qtpl:146
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:148
func streamspanJson(qw422016 *qt422016.Writer, span *span) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:148
	qw422016.N().S(`{"duration":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:150
	qw422016.N().DL(span.duration)
//line app/vtselect/traces/jaeger/jaeger.qtpl:150
	qw422016.N().S(`,"logs":[`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:152
	if len(span.logs) > 0 {
//line app/vtselect/traces/jaeger/jaeger.qtpl:153
		streamlogJson(qw422016, span.logs[0])
//line app/vtselect/traces/jaeger/jaeger.qtpl:154
		for _, v := range span.logs[1:] {
//line app/vtselect/traces/jaeger/jaeger.qtpl:154
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:155
			streamlogJson(qw422016, v)
//line app/vtselect/traces/jaeger/jaeger.qtpl:156
		}
//line app/vtselect/traces/jaeger/jaeger.qtpl:157
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:157
	qw422016.N().S(`],"operationName":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:159
	qw422016.N().Q(span.operationName)
//line app/vtselect/traces/jaeger/jaeger.qtpl:159
	qw422016.N().S(`,"processID":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:160
	qw422016.N().Q(span.processID)
//line app/vtselect/traces/jaeger/jaeger.qtpl:160
	qw422016.N().S(`,"references": [`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:162
	if len(span.references) > 0 {
//line app/vtselect/traces/jaeger/jaeger.qtpl:163
		streamspanRefJson(qw422016, span.references[0])
//line app/vtselect/traces/jaeger/jaeger.qtpl:164
		for _, v := range span.references[1:] {
//line app/vtselect/traces/jaeger/jaeger.qtpl:164
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:165
			streamspanRefJson(qw422016, v)
//line app/vtselect/traces/jaeger/jaeger.qtpl:166
		}
//line app/vtselect/traces/jaeger/jaeger.qtpl:167
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:167
	qw422016.N().S(`],"spanID":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:169
	qw422016.N().Q(span.spanID)
//line app/vtselect/traces/jaeger/jaeger.qtpl:169
	qw422016.N().S(`,"startTime":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:170
	qw422016.N().DL(span.startTime)
//line app/vtselect/traces/jaeger/jaeger.qtpl:170
	qw422016.N().S(`,"tags": [`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:172
	if len(span.tags) > 0 {
//line app/vtselect/traces/jaeger/jaeger.qtpl:173
		streamtagJson(qw422016, span.tags[0])
//line app/vtselect/traces/jaeger/jaeger.qtpl:174
		for _, v := range span.tags[1:] {
//line app/vtselect/traces/jaeger/jaeger.qtpl:174
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:175
			streamtagJson(qw422016, v)
//line app/vtselect/traces/jaeger/jaeger.qtpl:176
		}
//line app/vtselect/traces/jaeger/jaeger.qtpl:177
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:177
	qw422016.N().S(`],"traceID":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:179
	qw422016.N().Q(span.traceID)
//line app/vtselect/traces/jaeger/jaeger.qtpl:179
	qw422016.N().S(`,"warnings":null}`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:182
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:182
func writespanJson(qq422016 qtio422016.Writer, span *span) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:182
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:182
	streamspanJson(qw422016, span)
//line app/vtselect/traces/jaeger/jaeger.qtpl:182
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:182
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:182
func spanJson(span *span) string {
//line app/vtselect/traces/jaeger/jaeger.qtpl:182
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/jaeger.qtpl:182
	writespanJson(qb422016, span)
//line app/vtselect/traces/jaeger/jaeger.qtpl:182
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/jaeger.qtpl:182
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:182
	return qs422016
//line app/vtselect/traces/jaeger/jaeger.qtpl:182
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:184
func streamtagJson(qw422016 *qt422016.Writer, tag keyValue) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:184
	qw422016.N().S(`{"key":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:186
	qw422016.N().Q(tag.key)
//line app/vtselect/traces/jaeger/jaeger.qtpl:186
	qw422016.N().S(`,"type":"string","value":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:188
	qw422016.N().Q(tag.vStr)
//line app/vtselect/traces/jaeger/jaeger.qtpl:188
	qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:190
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:190
func writetagJson(qq422016 qtio422016.Writer, tag keyValue) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:190
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:190
	streamtagJson(qw422016, tag)
//line app/vtselect/traces/jaeger/jaeger.qtpl:190
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:190
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:190
func tagJson(tag keyValue) string {
//line app/vtselect/traces/jaeger/jaeger.qtpl:190
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/jaeger.qtpl:190
	writetagJson(qb422016, tag)
//line app/vtselect/traces/jaeger/jaeger.qtpl:190
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/jaeger.qtpl:190
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:190
	return qs422016
//line app/vtselect/traces/jaeger/jaeger.qtpl:190
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:192
func streamlogJson(qw422016 *qt422016.Writer, l log) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:192
	qw422016.N().S(`{"timestamp":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:194
	qw422016.N().DL(l.timestamp)
//line app/vtselect/traces/jaeger/jaeger.qtpl:194
	qw422016.N().S(`,"fields":[`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:196
	if len(l.fields) > 0 {
//line app/vtselect/traces/jaeger/jaeger.qtpl:197
		streamtagJson(qw422016, l.fields[0])
//line app/vtselect/traces/jaeger/jaeger.qtpl:198
		for _, v := range l.fields[1:] {
//line app/vtselect/traces/jaeger/jaeger.qtpl:198
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:199
			streamtagJson(qw422016, v)
//line app/vtselect/traces/jaeger/jaeger.qtpl:200
		}
//line app/vtselect/traces/jaeger/jaeger.qtpl:201
	}
//line app/vtselect/traces/jaeger/jaeger.qtpl:201
	qw422016.N().S(`]}`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:204
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:204
func writelogJson(qq422016 qtio422016.Writer, l log) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:204
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:204
	streamlogJson(qw422016, l)
//line app/vtselect/traces/jaeger/jaeger.qtpl:204
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:204
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:204
func logJson(l log) string {
//line app/vtselect/traces/jaeger/jaeger.qtpl:204
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/jaeger.qtpl:204
	writelogJson(qb422016, l)
//line app/vtselect/traces/jaeger/jaeger.qtpl:204
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/jaeger.qtpl:204
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:204
	return qs422016
//line app/vtselect/traces/jaeger/jaeger.qtpl:204
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:206
func streamspanRefJson(qw422016 *qt422016.Writer, ref spanRef) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:206
	qw422016.N().S(`{"refType":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:208
	qw422016.N().Q(ref.refType)
//line app/vtselect/traces/jaeger/jaeger.qtpl:208
	qw422016.N().S(`,"spanID":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:209
	qw422016.N().Q(ref.spanID)
//line app/vtselect/traces/jaeger/jaeger.qtpl:209
	qw422016.N().S(`,"traceID":`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:210
	qw422016.N().Q(ref.traceID)
//line app/vtselect/traces/jaeger/jaeger.qtpl:210
	qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/jaeger.qtpl:212
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:212
func writespanRefJson(qq422016 qtio422016.Writer, ref spanRef) {
//line app/vtselect/traces/jaeger/jaeger.qtpl:212
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:212
	streamspanRefJson(qw422016, ref)
//line app/vtselect/traces/jaeger/jaeger.qtpl:212
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:212
}

//line app/vtselect/traces/jaeger/jaeger.qtpl:212
func spanRefJson(ref spanRef) string {
//line app/vtselect/traces/jaeger/jaeger.qtpl:212
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/jaeger.qtpl:212
	writespanRefJson(qb422016, ref)
//line app/vtselect/traces/jaeger/jaeger.qtpl:212
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/jaeger.qtpl:212
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/jaeger.qtpl:212
	return qs422016
//line app/vtselect/traces/jaeger/jaeger.qtpl:212
}
